// "sign_billboard.h" generated by "Obj2Header.exe" [Version 1.9d] Author: L.Norri Fullsail University.
// Data is converted to left-handed coordinate system and UV data is V flipped for Direct3D/Vulkan.
// The companion file "sign_billboard.h2b" is a binary dump of this format(-padding) for more flexibility.
// Loading *.h2b: read version, sizes, handle strings(max len 260) by reading until null-terminated.
/***********************/
/*  Generator version  */
/***********************/
#ifndef _sign_billboard_version_
const char sign_billboard_version[4] = { '0','1','9','d' };
#define _sign_billboard_version_
#endif
/************************************************/
/*  This section contains the model's size data */
/************************************************/
#ifndef _sign_billboard_vertexcount_
const unsigned sign_billboard_vertexcount = 48;
#define _sign_billboard_vertexcount_
#endif
#ifndef _sign_billboard_indexcount_
const unsigned sign_billboard_indexcount = 96;
#define _sign_billboard_indexcount_
#endif
#ifndef _sign_billboard_materialcount_
const unsigned sign_billboard_materialcount = 3; // can be used for batched draws
#define _sign_billboard_materialcount_
#endif
#ifndef _sign_billboard_meshcount_
const unsigned sign_billboard_meshcount = 3;
#define _sign_billboard_meshcount_
#endif
/************************************************/
/*  This section contains the raw data to load  */
/************************************************/
#ifndef __OBJ_VEC3__
typedef struct _OBJ_VEC3_
{
	float x,y,z; // 3D Coordinate.
}OBJ_VEC3;
#define __OBJ_VEC3__
#endif
#ifndef __OBJ_VERT__
typedef struct _OBJ_VERT_
{
	OBJ_VEC3 pos; // Left-handed +Z forward coordinate w not provided, assumed to be 1.
	OBJ_VEC3 uvw; // D3D/Vulkan style top left 0,0 coordinate.
	OBJ_VEC3 nrm; // Provided direct from obj file, may or may not be normalized.
}OBJ_VERT;
#define __OBJ_VERT__
#endif
#ifndef _sign_billboard_vertices_
// Raw Vertex Data follows: Positions, Texture Coordinates and Normals.
const OBJ_VERT sign_billboard_vertices[48] =
{
	{	{ 0.012500f, 1.620000f, 0.300000f },	{ -0.492126f, 12.811020f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ 0.037500f, 1.620000f, 0.300000f },	{ -1.476378f, 12.811020f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ 0.037500f, 1.620000f, -0.300000f },	{ -1.476378f, -10.811020f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ 0.012500f, 1.620000f, -0.300000f },	{ -0.492126f, -10.811020f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ 0.037500f, 1.620000f, -0.300000f },	{ 1.476378f, -62.779530f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.037500f, 0.020000f, -0.300000f },	{ 1.476378f, 0.212598f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.012500f, 0.020000f, -0.300000f },	{ 0.492126f, 0.212598f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.012500f, 1.620000f, -0.300000f },	{ 0.492126f, -62.779530f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ -0.037500f, 0.020000f, -0.300000f },	{ -1.476378f, 0.212598f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ -0.037500f, 0.000000f, -0.300000f },	{ -1.476378f, 1.000000f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.037500f, 0.000000f, -0.300000f },	{ 1.476378f, 1.000000f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.012500f, 0.020000f, 0.300000f },	{ -11.811020f, 0.212598f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.012500f, 1.620000f, 0.300000f },	{ -11.811020f, -62.779530f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.012500f, 0.070799f, 0.249202f },	{ -9.811082f, -1.787343f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.012500f, 0.020000f, -0.300000f },	{ 11.811020f, 0.212598f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.012500f, 0.070799f, -0.249202f },	{ 9.811082f, -1.787343f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.012500f, 1.569201f, -0.249202f },	{ 9.811082f, -60.779591f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.012500f, 1.569201f, 0.249202f },	{ -9.811082f, -60.779591f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.012500f, 1.620000f, -0.300000f },	{ 11.811020f, -62.779530f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.037500f, 0.020000f, 0.300000f },	{ 1.476378f, 0.212598f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ -0.037500f, 0.000000f, 0.300000f },	{ 1.476378f, 1.000000f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.037500f, 0.000000f, 0.300000f },	{ -1.476378f, 1.000000f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.037500f, 0.020000f, 0.300000f },	{ -1.476378f, 0.212598f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.012500f, 0.020000f, 0.300000f },	{ -0.492126f, 0.212598f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.012500f, 1.620000f, 0.300000f },	{ -0.492126f, -62.779530f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.037500f, 1.620000f, 0.300000f },	{ -1.476378f, -62.779530f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ -0.037500f, 0.000000f, -0.300000f },	{ -1.476378f, -10.811020f, 0.000000f },	{ 0.000000f, -1.000000f, -0.000000f }	},
	{	{ 0.037500f, 0.000000f, -0.300000f },	{ 1.476378f, -10.811020f, 0.000000f },	{ 0.000000f, -1.000000f, -0.000000f }	},
	{	{ 0.037500f, 0.000000f, 0.300000f },	{ 1.476378f, 12.811020f, 0.000000f },	{ 0.000000f, -1.000000f, -0.000000f }	},
	{	{ -0.037500f, 0.000000f, 0.300000f },	{ -1.476378f, 12.811020f, 0.000000f },	{ 0.000000f, -1.000000f, -0.000000f }	},
	{	{ 0.037500f, 0.020000f, -0.300000f },	{ -11.811020f, 0.212598f, 0.000000f },	{ 1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.037500f, 0.020000f, 0.300000f },	{ 11.811020f, 0.212598f, 0.000000f },	{ 1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.037500f, 0.000000f, 0.300000f },	{ 11.811020f, 1.000000f, 0.000000f },	{ 1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.037500f, 0.000000f, -0.300000f },	{ -11.811020f, 1.000000f, 0.000000f },	{ 1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.037500f, 0.000000f, -0.300000f },	{ 11.811020f, 1.000000f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.037500f, 0.000000f, 0.300000f },	{ -11.811020f, 1.000000f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.037500f, 0.020000f, 0.300000f },	{ -11.811020f, 0.212598f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.037500f, 0.020000f, -0.300000f },	{ 11.811020f, 0.212598f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.037500f, 0.020000f, 0.300000f },	{ 1.476378f, 12.811020f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ 0.012500f, 0.020000f, 0.300000f },	{ -0.492126f, 12.811020f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ 0.012500f, 0.020000f, -0.300000f },	{ -0.492126f, -10.811020f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ -0.037500f, 0.020000f, -0.300000f },	{ 1.476378f, -10.811020f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ 0.037500f, 1.620000f, -0.300000f },	{ -9.811082f, -60.779591f, 0.000000f },	{ 1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.037500f, 1.620000f, 0.300000f },	{ 9.811082f, -60.779591f, 0.000000f },	{ 1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.037500f, 0.020000f, 0.300000f },	{ 9.811082f, -1.787343f, 0.000000f },	{ 1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.037500f, 0.020000f, 0.300000f },	{ -9.811082f, -60.779591f, 0.000000f },	{ 1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.037500f, 0.020000f, -0.300000f },	{ 9.811082f, -60.779591f, 0.000000f },	{ 1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.037500f, 1.620000f, -0.300000f },	{ 9.811082f, -1.787343f, 0.000000f },	{ 1.000000f, 0.000000f, -0.000000f }	},
};
#define _sign_billboard_vertices_
#endif
#ifndef _sign_billboard_indices_
// Index Data follows: Sequential by mesh, Every Three Indices == One Triangle.
const unsigned int sign_billboard_indices[96] =
{
	 0, 1, 2,
	 2, 3, 0,
	 4, 5, 6,
	 6, 7, 4,
	 8, 6, 5,
	 9, 8, 5,
	 5, 10, 9,
	 11, 12, 13,
	 13, 14, 11,
	 13, 15, 14,
	 15, 16, 14,
	 17, 13, 12,
	 12, 18, 17,
	 18, 16, 17,
	 18, 14, 16,
	 19, 20, 21,
	 21, 22, 19,
	 22, 23, 19,
	 22, 24, 23,
	 22, 25, 24,
	 26, 27, 28,
	 28, 29, 26,
	 30, 31, 32,
	 32, 33, 30,
	 34, 35, 36,
	 36, 37, 34,
	 38, 39, 40,
	 40, 41, 38,
	 15, 13, 17,
	 17, 16, 15,
	 42, 43, 44,
	 45, 46, 47,
};
#define _sign_billboard_indices_
#endif
// Part of an OBJ_MATERIAL, the struct is 16 byte aligned so it is GPU register friendly.
#ifndef __OBJ_ATTRIBUTES__
typedef struct _OBJ_ATTRIBUTES_
{
	OBJ_VEC3    Kd; // diffuse reflectivity
	float	    d; // dissolve (transparency) 
	OBJ_VEC3    Ks; // specular reflectivity
	float       Ns; // specular exponent
	OBJ_VEC3    Ka; // ambient reflectivity
	float       sharpness; // local reflection map sharpness
	OBJ_VEC3    Tf; // transmission filter
	float       Ni; // optical density (index of refraction)
	OBJ_VEC3    Ke; // emissive reflectivity
	unsigned    illum; // illumination model
}OBJ_ATTRIBUTES;
#define __OBJ_ATTRIBUTES__
#endif
// This structure also has been made GPU register friendly so it can be transfered directly if desired.
// Note: Total struct size will vary depenedening on CPU processor architecture (string pointers).
#ifndef __OBJ_MATERIAL__
typedef struct _OBJ_MATERIAL_
{
	// The following items are typically used in a pixel/fragment shader, they are packed for GPU registers.
	OBJ_ATTRIBUTES attrib; // Surface shading characteristics & illumination model
	// All items below this line are not needed on the GPU and are generally only used during load time.
	const char* name; // the name of this material
	// If the model's materials contain any specific texture data it will be located below.
	const char* map_Kd; // diffuse texture
	const char* map_Ks; // specular texture
	const char* map_Ka; // ambient texture
	const char* map_Ke; // emissive texture
	const char* map_Ns; // specular exponent texture
	const char* map_d; // transparency texture
	const char* disp; // roughness map (displacement)
	const char* decal; // decal texture (lerps texture & material colors)
	const char* bump; // normal/bumpmap texture
	void* padding[2]; // 16 byte alignment on 32bit or 64bit
}OBJ_MATERIAL;
#define __OBJ_MATERIAL__
#endif
#ifndef _sign_billboard_materials_
// Material Data follows: pulled from a .mtl file of the same name if present.
const OBJ_MATERIAL sign_billboard_materials[3] =
{
	{
		{{ 0.560784f, 0.568627f, 0.600000f },
		1.000000f,
		{ 0.200000f, 0.200000f, 0.200000f },
		500.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		60.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		1.500000f,
		{ 0.000000f, 0.000000f, 0.000000f },
		2},
		"border",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
	},
	{
		{{ 0.337255f, 0.737255f, 0.600000f },
		1.000000f,
		{ 0.200000f, 0.200000f, 0.200000f },
		500.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		60.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		1.500000f,
		{ 0.000000f, 0.000000f, 0.000000f },
		2},
		"roof",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
	},
	{
		{{ 0.764151f, 0.764151f, 0.764151f },
		1.000000f,
		{ 0.200000f, 0.200000f, 0.200000f },
		500.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		60.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		1.500000f,
		{ 0.000000f, 0.000000f, 0.000000f },
		2},
		"_defaultMat",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
	},
};
#define _sign_billboard_materials_
#endif
/************************************************/
/*  This section contains the model's structure */
/************************************************/
#ifndef _sign_billboard_batches_
// Use this conveinence array to batch render all geometry by like material.
// Each entry corresponds to the same entry in the materials array above.
// The two numbers provided are the IndexCount and the IndexOffset into the indices array.
// If you need more fine grained control(ex: for transformations) use the OBJ_MESH data below.
const unsigned int sign_billboard_batches[3][2] =
{
	{ 84, 0 },
	{ 6, 84 },
	{ 6, 90 },
};
#define _sign_billboard_batches_
#endif
#ifndef __OBJ_MESH__
typedef struct _OBJ_MESH_
{
	const char* name;
	unsigned    indexCount;
	unsigned    indexOffset;
	unsigned    materialIndex;
}OBJ_MESH;
#define __OBJ_MESH__
#endif
#ifndef _sign_billboard_meshes_
// Mesh Data follows: Meshes are .obj groups sorted & split by material.
// Meshes are provided in sequential order, sorted by material first and name second.
const OBJ_MESH sign_billboard_meshes[3] =
{
	{
		"sign_billboard",
		84,
		0,
		0,
	},
	{
		"sign_billboard",
		6,
		84,
		1,
	},
	{
		"sign_billboard",
		6,
		90,
		2,
	},
};
#define _sign_billboard_meshes_
#endif
